name: Release

on:
  push:
    tags:
      - 'v*'  # 當推送標籤以'v'開頭時觸發，例如 v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Build for multiple platforms
        run: |
          set -e
          # 建立發佈用的資料夾
          mkdir -p releases

          # 編譯 Linux 版本
          GOOS=linux GOARCH=amd64 go build -o releases/gsh-linux-amd64 ./cmd
          GOOS=linux GOARCH=arm64 go build -o releases/gsh-linux-arm64 ./cmd

          # 編譯 Windows 版本
          GOOS=windows GOARCH=amd64 go build -o releases/gsh-windows-amd64.exe ./cmd

          # 編譯 macOS 版本
          GOOS=darwin GOARCH=amd64 go build -o releases/gsh-darwin-amd64 ./cmd
          GOOS=darwin GOARCH=arm64 go build -o releases/gsh-darwin-arm64 ./cmd

          # 檢查 build 結果
          ls -lh releases

          # 壓縮檔案
          cd releases
          for file in *; do
            zip "${file}.zip" "$file"
            rm "$file"
          done
          cd ..

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
